version: '3.9'

networks:
  proxy.front-network:
    driver: bridge

services:
  app:
    image: w-service:1
    ports:
      - 8080:8080
    networks:
      - proxy.front-network
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password


  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_db
    networks:
      - proxy.front-network