version: '3.9'

services:

  db:
    image: postgres:16
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=anton
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_db