spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: anton
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none

